# https://github.com/apache/airflow/blob/main/chart/values.yaml

createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false

config:
  webserver:
    expose_config: 'True'  # by default this is 'False'

env:
  - name: "AIRFLOW_VAR_KEY"
    value: "value_1"
  - name: "AIRFLOW_VAR_ANOTHER_KEY"
    value: "value_2"

dags:
  persistence:
    enabled: true
  gitSync:
    enabled: true
    repo: https://github.com/Celsuss/Amazon-review-text-classification.git
    branch: main
    subPath: airflow/
    depth: 1
    period: 10s
